// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggtgwndgilhnlxcwhtdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdndGd3bmRnaWxobmx4Y3dodGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDg0MjgsImV4cCI6MjA3MTQyNDQyOH0.6Iymfw0wV5JpyNaiXQgmj5NwyMZ8fIze3Q4pLLio8hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});